# Generated by Django 6.0.4 on 2026-07-04 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='ommprakashrout@example.com', max_length=254)),
                ('phone', models.CharField(default='+91 98765 43210', max_length=30)),
                ('location', models.CharField(default='Bhubaneswar, India', max_length=200)),
                ('contact_tagline', models.TextField(default="I'm always open to discussing exciting projects and new opportunities. Let's collaborate!")),
            ],
            options={
                'verbose_name': 'Contact Info',
                'verbose_name_plural': 'Contact Info',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Omm Prakash Rout', max_length=100)),
                ('title', models.CharField(default='Software Engineer & Developer', max_length=200)),
                ('typewriter_roles', models.CharField(default='Full Stack Developer,Python Enthusiast,Cloud Architect,Software Engineer', help_text='Comma-separated roles for the typewriter animation', max_length=500)),
                ('bio_short', models.TextField(default='I create beautiful, functional, and user-centered digital experiences. With a strong passion for web development, I bring ideas to life through clean code and thoughtful design.')),
                ('bio_long', models.TextField(default="I'm a creative thinker and developer passionate about building modern, responsive web applications. My journey began with a love for problem-solving and evolved into a deep curiosity for how the web works — combining logic with creativity to bring ideas to life.")),
                ('image', models.ImageField(blank=True, null=True, upload_to='profile/')),
                ('resume', models.FileField(blank=True, null=True, upload_to='resume/')),
                ('is_available', models.BooleanField(default=True)),
                ('availability_text', models.CharField(default='Available for freelance work', max_length=100)),
                ('languages', models.CharField(default='JS, Python, Java, SQL', max_length=200)),
                ('education', models.CharField(default='Computer Science', max_length=200)),
                ('projects_count', models.CharField(default='15+ Built Projects', max_length=50)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profile',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('tags', models.CharField(help_text="Comma-separated tags, e.g. 'Python, Django, REST API'", max_length=300)),
                ('github_url', models.URLField(blank=True)),
                ('live_url', models.URLField(blank=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower = first)')),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon_class', models.CharField(help_text="Phosphor icon class, e.g. 'ph ph-database'", max_length=100)),
                ('category', models.CharField(choices=[('language', 'Programming Language'), ('framework', 'Framework'), ('database', 'Database'), ('tool', 'Tool / Platform'), ('other', 'Other')], default='other', max_length=20)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower = first)')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('github', 'GitHub'), ('linkedin', 'LinkedIn'), ('instagram', 'Instagram'), ('twitter', 'Twitter/X'), ('youtube', 'YouTube'), ('other', 'Other')], max_length=20)),
                ('url', models.URLField()),
                ('icon_class', models.CharField(help_text="Phosphor icon class, e.g. 'ph ph-github-logo'", max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
